Watching for file changes with StatReloader
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Not Found: /
"GET / HTTP/1.1" 404 179
Not Found: /listeners
"GET /listeners HTTP/1.1" 404 179
Unable to validate token: Could not find versioned identity endpoints when attempting to authenticate. Please check that your auth_url is correct. Unable to establish connection to https://keystone.cloud.seda.club: HTTPSConnectionPool(host='keystone.cloud.seda.club', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113a41010>: Failed to resolve 'keystone.cloud.seda.club' ([Errno 8] nodename nor servname provided, or not known)"))
Invalid user token
Not Found: /listeners
"GET /listeners HTTP/1.1" 404 179
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Unable to validate token: Unable to establish connection to https://keystone.cloud.seda.club/v3/auth/tokens: HTTPSConnectionPool(host='keystone.cloud.seda.club', port=443): Max retries exceeded with url: /v3/auth/tokens (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105046b10>: Failed to resolve 'keystone.cloud.seda.club' ([Errno 8] nodename nor servname provided, or not known)"))
Invalid user token
Not Found: /listeners
"GET /listeners HTTP/1.1" 404 179
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Not Found: /listeners
"GET /listeners HTTP/1.1" 404 179
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Not Found: /listeners
"GET /listeners HTTP/1.1" 404 179
Not Found: /listeners
"GET /listeners HTTP/1.1" 404 179
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 79, in authenticated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 29, in get
    listeners = Listener.objects.filter(**filters).order_by("-created_on")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.db.models.manager.BaseManager._get_queryset_methods.<locals>.create_method.<locals>.manager_method() argument after ** must be a mapping, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/settings.py", line 179, in import_from_string
    return import_string(val)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'envoy_translater.api.exception_handler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'envoy_translater.api.exception_handler.exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'envoy_translater.api.exception_handler'.
"GET /listeners HTTP/1.1" 500 145
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 79, in authenticated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 29, in get
    listeners = Listener.objects.filter(**filters).order_by("-created_on")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.db.models.manager.BaseManager._get_queryset_methods.<locals>.create_method.<locals>.manager_method() argument after ** must be a mapping, not NoneType
"GET /listeners HTTP/1.1" 500 145
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: listeners_listener

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 79, in authenticated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/utils.py", line 37, in parse_filters
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 48, in get
    for listener in listeners:
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: listeners_listener
"GET /listeners HTTP/1.1" 500 145
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: listeners_listener

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 79, in authenticated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/utils.py", line 37, in parse_filters
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 48, in get
    for listener in listeners:
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: listeners_listener
"GET /listeners HTTP/1.1" 500 145
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: listeners_listener

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 79, in authenticated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/utils.py", line 37, in parse_filters
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 48, in get
    for listener in listeners:
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: listeners_listener
"GET /listeners HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/migrations/0001_initial.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /listeners HTTP/1.1" 200 16
"GET /listeners HTTP/1.1" 200 16
"GET /listeners HTTP/1.1" 200 16
"GET /listeners HTTP/1.1" 200 16
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 70, in post
    listener_name=request.data["listener_name"],
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'listener_name'
"POST /listeners HTTP/1.1" 500 145
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 71, in post
    description=request.data["description"],
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'description'
"POST /listeners HTTP/1.1" 500 145
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 74, in post
    type=request.data["type"],
         ~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
"POST /listeners HTTP/1.1" 500 145
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tls'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 69, in post
    listener = Listener.objects.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
                 ^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 837, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'type' expected a number but got 'tls'.
"POST /listeners HTTP/1.1" 500 145
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 77, in post
    return Response({"listener": listener.to_dict()})
                                 ^^^^^^^^^^^^^^^^
AttributeError: 'Listener' object has no attribute 'to_dict'
"POST /listeners HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 77, in post
    return Response({"listener": listener.to_dict()})
                                 ^^^^^^^^^^^^^^^^
AttributeError: 'Listener' object has no attribute 'to_dict'
"POST /listeners HTTP/1.1" 500 145
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 77, in post
    return Response({"listener": listener.to_dict()})
                                 ^^^^^^^^^^^^^^^^
AttributeError: 'Listener' object has no attribute 'to_dict'
"POST /listeners HTTP/1.1" 500 145
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 79, in authenticated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/utils.py", line 37, in parse_filters
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 49, in get
    listener_list.append(listener.to_dict())
                         ^^^^^^^^^^^^^^^^
AttributeError: 'Listener' object has no attribute 'to_dict'
"GET /listeners HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /listeners HTTP/1.1" 200 530
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /listeners HTTP/1.1" 200 16
"POST /listeners HTTP/1.1" 200 185
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: listeners_listener.ip, listeners_listener.port

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 69, in post
    listener = Listener.objects.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: listeners_listener.ip, listeners_listener.port
"POST /listeners HTTP/1.1" 500 145
"GET /listeners HTTP/1.1" 200 188
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/migrations/0001_initial.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /listeners HTTP/1.1" 200 16
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 73, in post
    external_ip=request.data["external_ip"],
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'external_ip'
"POST /listeners HTTP/1.1" 500 145
"POST /listeners HTTP/1.1" 200 217
"GET /listeners HTTP/1.1" 200 220
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/exceptions.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/urls.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /listeners HTTP/1.1" 200 220
Not Found: /routs
"GET /routs HTTP/1.1" 404 179
Internal Server Error: /routes
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 79, in authenticated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/utils.py", line 37, in parse_filters
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 97, in get
    routes = Route.objects.all().order_by("-created_on")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1149, in order_by
    obj.query.add_ordering(*field_names)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 2016, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'created_on' into field. Choices are: domain_names, keystone_user, listener, listener_id, project_id, target_servers, uuid
"GET /routes HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/migrations/0001_initial.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /listeners HTTP/1.1" 200 16
Internal Server Error: /routes
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 79, in authenticated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/utils.py", line 37, in parse_filters
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 97, in get
    routes = Route.objects.all().order_by("-created_on")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1149, in order_by
    obj.query.add_ordering(*field_names)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 2016, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'created_on' into field. Choices are: domain_names, keystone_user, listener, listener_id, project_id, target_servers, uuid
"GET /routes HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/listeners/models.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /routes HTTP/1.1" 200 13
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /routes HTTP/1.1" 200 13
Internal Server Error: /routes
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 79, in authenticated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/utils.py", line 37, in parse_filters
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 97, in get
    filters["project_id__exact"] = project_id
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
"GET /routes?project_id=1 HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /routes?project_id=1 HTTP/1.1" 200 13
"GET /routes HTTP/1.1" 200 13
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /routes HTTP/1.1" 200 13
"GET /routes?project_id=null HTTP/1.1" 200 13
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /routes?project_id=null HTTP/1.1" 200 13
"GET /listeners HTTP/1.1" 200 16
"POST /listeners HTTP/1.1" 200 217
"GET /listeners HTTP/1.1" 200 220
Unauthorized: /routes
"POST /routes HTTP/1.1" 401 51
Internal Server Error: /routes
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 49, in mod_or_admin
    return require_roles(
           ^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 139, in post
    listener = Listener.objects.get(id=request.keystone_user["listener_id"])
                                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'listener_id'
"POST /routes HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Internal Server Error: /routes
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 49, in mod_or_admin
    return require_roles(
           ^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 139, in post
    listener = Listener.objects.get(id=request.data["listener_id"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. Choices are: created_on, description, external_ip, ip, listener_name, port, route, type, uuid
"POST /routes HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"POST /routes HTTP/1.1" 200 356
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Bad Request: /routes
"POST /routes HTTP/1.1" 400 40
Bad Request: /routes
"POST /routes HTTP/1.1" 400 40
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"POST /routes HTTP/1.1" 200 317
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/urls.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Internal Server Error: /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 3210, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 3125, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'listener_id'
"GET /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9 HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/urls.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Internal Server Error: /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/utils.py", line 37, in parse_filters
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 88, in get
    listener = Listener.objects.get(id=listener_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. Choices are: created_on, description, external_ip, ip, listener_name, port, route, type, uuid
"GET /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9 HTTP/1.1" 500 145
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
"GET /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9 HTTP/1.1" 200 217
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Not Found: /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9/routes
"GET /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9/routes HTTP/1.1" 404 179
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Not Found: /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9/routes
"GET /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9/routes HTTP/1.1" 404 179
Not Found: /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9/routes/
"GET /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9/routes/ HTTP/1.1" 404 179
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Not Found: /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9/routes/
"GET /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9/routes/ HTTP/1.1" 404 179
"GET /listeners/564cfa1ef69f4968a7ce4ebcaaf85bc9 HTTP/1.1" 200 883
/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py changed, reloading.
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
Bad Request: /listeners
"POST /listeners HTTP/1.1" 400 27
Internal Server Error: /listeners
Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: listeners_listener.ip, listeners_listener.port

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 67, in admin
    return require_roles({"admin"}, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/utils.py", line 36, in require_roles
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/envoy_translater/api/views.py", line 75, in post
    listener = Listener.objects.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syeyoung/Documents/semicolon/openstacks/envoy_translater/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: listeners_listener.ip, listeners_listener.port
"POST /listeners HTTP/1.1" 500 145
"GET /routes?project_id=null HTTP/1.1" 200 667
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
Watching for file changes with StatReloader
Starting Keystone auth_token middleware
The option "username" is not known to keystonemiddleware
The option "password" is not known to keystonemiddleware
The option "project_name" is not known to keystonemiddleware
The option "project_domain_id" is not known to keystonemiddleware
The option "user_domain_id" is not known to keystonemiddleware
The option "auth_url" is not known to keystonemiddleware
AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
